image: node:lts-gallium

options:
  max-time: 6

definitions:
  steps:
    - step: &sonarqube-step
        name: SonarQube analysis
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
    - step: &install-step
        name: Installing
        caches:
          - node
        script:
          - npm install
    - step: &build-step
        name: Building
        caches:
          - node
        script:
          - npm run build
          - cd dist
          - if [ ! -f "index.js" ]; then exit 1; fi
    - step: &lint-step
        name: Linting
        caches:
          - node
        script:
          - npm run lint
          - echo "Fanfare!"
    - step: &test-step
        name: Testing
        caches:
          - node
        script:
          - npm run test --verbose --forceExit
          - echo "Fanfare!"

  caches:
    sonar: ~/.sonar

clone:
  depth: full

pipelines:
  pull-requests:
    "**":
      - step: *install-step
      - parallel:
          - step: *build-step
          - step: *lint-step
          - step: *test-step
  branches:
    "{master}":
      - step: *install-step
      - parallel:
          - step: *build-step
          - step: *lint-step
  custom:
    sonar:
      - step: *sonarqube-step
